[package]
name = "lindera-dictionary"
version = "0.8.1"
edition = "2018"
description = "A morphological dictionary loader."
documentation = "https://docs.rs/lindera-dictionary"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "dictionary", "directory", "loader"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
byteorder = "1.4"

lindera-core = { version = "0.8.1", path = "../lindera-core" }
