[package]
name = "lindera-dictionary"
version = "0.27.1"
edition = "2021"
description = "A Japanese morphological dictionary."
documentation = "https://docs.rs/lindera-dictionary"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
ipadic = ["lindera-ipadic/ipadic"]  # Include Japanese dictionary (IPADIC)
ipadic-compress = ["lindera-ipadic/compress"]  # Compress Japanese dictionary (IPADIC)
ipadic-neologd = ["lindera-ipadic-neologd/ipadic-neologd"]  # Include Japanese dictionary (IPADIC NEologd)
ipadic-neologd-compress = ["lindera-ipadic-neologd/compress"]  # Compress Japanese dictionary (IPADIC NEologd)
unidic = ["lindera-unidic/unidic"]  # Include Japanese dictionary (UniDic)
unidic-compress = ["lindera-unidic/compress"]  # Compress Japanese dictionary (UniDic)
ko-dic = ["lindera-ko-dic/ko-dic"]  # Include Korean dictionary (ko-dic)
ko-dic-compress = ["lindera-ko-dic/compress"]  # Compress Korean dictionary (ko-dic)
cc-cedict = ["lindera-cc-cedict/cc-cedict"]  # Include Chinese dictionary (CC-CEDICT)
cc-cedict-compress = ["lindera-cc-cedict/compress"]  # Compress Chinese dictionary (CC-CEDICT)

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
byteorder = "1.4.3"
serde = { version="1.0.167", features = ["derive"] }

lindera-core = { version = "0.27.1", path = "../lindera-core" }
lindera-cc-cedict = { version = "0.27.1", path = "../lindera-cc-cedict", optional = true }
lindera-cc-cedict-builder = { version = "0.27.1", path = "../lindera-cc-cedict-builder" }
lindera-ipadic = { version = "0.27.1", path = "../lindera-ipadic", optional = true }
lindera-ipadic-builder = { version = "0.27.1", path = "../lindera-ipadic-builder" }
lindera-ipadic-neologd = { version = "0.27.1", path = "../lindera-ipadic-neologd", optional = true }
lindera-ipadic-neologd-builder = { version = "0.27.1", path = "../lindera-ipadic-neologd-builder" }
lindera-ko-dic = { version = "0.27.1", path = "../lindera-ko-dic", optional = true }
lindera-ko-dic-builder = { version = "0.27.1", path = "../lindera-ko-dic-builder" }
lindera-unidic = { version = "0.27.1", path = "../lindera-unidic", optional = true }
lindera-unidic-builder = { version = "0.27.1", path = "../lindera-unidic-builder" }
