[workspace]
members = [
    "lindera-core",
    "lindera-ipadic-builder",
    "lindera-dictionary",
    "lindera-ipadic",
    "lindera",
    "lindera-cli",
    "lindera-compress",
    "lindera-decompress",
    "lindera-unidic-builder",
    "lindera-unidic",
]
resolver = "2"

[profile.release]
lto = true
