[package]
name = "lindera-cli"
version = "0.22.0"
edition = "2021"
description = "A morphological analysis command line interface."
documentation = "https://docs.rs/lindera-cli"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "cli"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
ipadic = ["lindera/ipadic"]  # Include Japanese dictionary (IPADIC)
unidic = ["lindera/unidic"]  # Include Japanese dictionary (UniDic)
ko-dic = ["lindera/ko-dic"]  # Include Korean dictionary (ko-dic)
cc-cedict = ["lindera/cc-cedict"]  # Include Chinese dictionary (CC-CEDICT)
ipadic-compress = ["lindera/ipadic-compress"]  # Compress Japanese dictionary (IPADIC)
unidic-compress = ["lindera/unidic-compress"]  # Compress Japanese dictionary (UniDic)
ko-dic-compress = ["lindera/ko-dic-compress"]  # Compress Korean dictionary (ko-dic)
cc-cedict-compress = ["lindera/cc-cedict-compress"]  # Compress Chinese dictionary (CC-CEDICT)

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive", "cargo"] }
serde_json = "1.0.91"

lindera = { version = "0.22.0", path = "../lindera" }

[[bin]]
name = "lindera"
path = "src/main.rs"
