[package]
name = "lindera-cli"
version = "0.13.3"
edition = "2021"
description = "A morphological analysis tool."
documentation = "https://docs.rs/lindera-cli"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "cli"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # no dictionary
full = ["ipadic", "unidic", "ko-dic", "cc-cedict"]
ipadic = ["lindera/ipadic"]  # Japanese dictionary
unidic = ["lindera/unidic"]  # Japanese dictionary
ko-dic = ["lindera/ko-dic"]  # Korean dictionary
cc-cedict = ["lindera/cc-cedict"]  # Chinese dictionary
compress = ["lindera/compress"]

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive", "cargo"] }

lindera = { version = "0.13.3", path = "../lindera" }

[[bin]]
name = "lindera"
path = "src/main.rs"
