[package]
name = "lindera-cli"
version = "0.12.1"
edition = "2021"
description = "A morphological analysis tool."
documentation = "https://docs.rs/lindera-cli"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "cli"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []
full = ["ipadic", "unidic", "ko-dic", "cc-cedict"]
ipadic = ["lindera/ipadic"]
unidic = ["lindera/unidic"]
ko-dic = ["lindera/ko-dic"]
cc-cedict = ["lindera/cc-cedict"]
compress = ["lindera/compress"]

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive", "cargo"] }
lindera = { version = "0.12.1", path = "../lindera" }

[[bin]]
name = "lindera"
path = "src/main.rs"
