[package]
name = "lindera-cli"
version = "0.23.1"
edition = "2021"
description = "A morphological analysis command line interface."
documentation = "https://docs.rs/lindera-cli"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "cli"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
ipadic = ["lindera/ipadic"]  # Include IPADIC dictionary (Japanese)
unidic = ["lindera/unidic"]  # Include UniDic dictionary (Japanese)
ko-dic = ["lindera/ko-dic"]  # Include ko-dic dictionary (Korean)
cc-cedict = ["lindera/cc-cedict"]  # Include CC-CEDICT dictionary (Chinese)
ipadic-filter = ["lindera/ipadic-filter"]  # Include filters for IPADIC
unidic-filter = ["lindera/unidic-filter"]  # Include filters for UniDic
ko-dic-filter = ["lindera/ko-dic-filter"]  # Include filters for ko-dic
cc-cedict-filter = ["lindera/cc-cedict-filter"]  # Include filters for CC-CEDICT
ipadic-compress = ["lindera/ipadic-compress"]  # Compress IPADIC
unidic-compress = ["lindera/unidic-compress"]  # Compress UniDic
ko-dic-compress = ["lindera/ko-dic-compress"]  # Compress ko-dic
cc-cedict-compress = ["lindera/cc-cedict-compress"]  # Compress CC-CEDICT

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive", "cargo"] }
serde_json = "1.0.91"

lindera = { version = "0.23.1", path = "../lindera" }

[[bin]]
name = "lindera"
path = "src/main.rs"
