[package]
name = "lindera-cli"
version = "0.17.0"
edition = "2021"
description = "A morphological analysis command line interface."
documentation = "https://docs.rs/lindera-cli"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "cli"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
full = ["ipadic", "unidic", "ko-dic", "cc-cedict"]  # All dictionaries included
cjk = ["cc-cedict", "ipadic", "ko-dic"] # CJK dictionaries included
ipadic = ["lindera/ipadic"]  # Japanese dictionary included
unidic = ["lindera/unidic"]  # Japanese dictionary included
ko-dic = ["lindera/ko-dic"]  # Korean dictionary included
cc-cedict = ["lindera/cc-cedict"]  # Chinese dictionary included
compress = ["lindera/compress"]

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.8", features = ["derive", "cargo"] }
serde_json = "1.0.82"

lindera = { version = "0.17.0", path = "../lindera" }

[[bin]]
name = "lindera"
path = "src/main.rs"
