[package]
name = "lindera-unidic"
version = "0.29.0"
edition = "2021"
description = "A Japanese morphological dictionary for UniDic."
documentation = "https://docs.rs/lindera-unidic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "unidic"]
categories = ["text-processing"]
license = "MIT"

[features]
unidic = ["encoding", "flate2", "tar", "ureq"]
compress = ["lindera-unidic-builder/compress", "lindera-decompress"]

[dependencies]
bincode.workspace = true
byteorder.workspace = true
once_cell.workspace = true

lindera-core.workspace = true
lindera-decompress = { workspace = true, optional = true }

[build-dependencies]
encoding = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
tar = { workspace =true, optional = true }
ureq = { workspace = true, optional = true }

lindera-core.workspace = true
lindera-unidic-builder.workspace = true
