[package]
name = "lindera-unidic"
version = "0.12.2"
edition = "2021"
description = "A Japanese morphological dictionary for UniDic."
documentation = "https://docs.rs/lindera-unidic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "loader", "unidic"]
categories = ["text-processing"]
license = "MIT"

[features]
unidic = ["encoding", "zip", "ureq"]
compress = ["lindera-unidic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1.3"

lindera-core = { version = "0.12.0", path = "../lindera-core" }
lindera-decompress = { version = "0.12.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2", optional = true }
zip = { version = "0.6", optional = true }
ureq = { version = "2.4.0", default-features = false, features = ["tls"], optional = true }

lindera-core = { version = "0.12.2", path = "../lindera-core" }
lindera-unidic-builder = { version = "0.12.2", path = "../lindera-unidic-builder"}
