[package]
name = "lindera-unidic"
version = "0.11.1"
edition = "2021"
description = "A Japanese morphological dictionary for UniDic."
documentation = "https://docs.rs/lindera-unidic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "loader", "unidic"]
categories = ["text-processing"]
license = "MIT"

[features]
unidic = []
compress = ["lindera-unidic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1.3"

lindera-core = { version = "0.11.1", path = "../lindera-core" }
lindera-decompress = { version = "0.11.1", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = "0.2"
reqwest = "0.11"
zip = "0.5"
tokio = { version = "1.9", features = ["full"] }

lindera-core = { version = "0.11.1", path = "../lindera-core" }
lindera-unidic-builder = { version = "0.11.1", path = "../lindera-unidic-builder"}
