[package]
name = "lindera-core"
version = "0.17.0"
edition = "2021"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera-core"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
byteorder = "1.4.3"
encoding_rs = "0.8.31"
log = "0.4.17"
serde = {version="1.0.138", features = ["derive"] }
thiserror = "1.0.31"
yada = "0.5.0"
