[package]
name = "lindera-cc-cedict"
version = "0.12.2"
edition = "2021"
description = "A Japanese morphological dictionary for CC-CEDICT."
documentation = "https://docs.rs/lindera-cc-cedict"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["chinese", "morphological", "dictionary", "loader", "cc-cedict"]
categories = ["text-processing"]
license = "MIT"

[features]
cc-cedict = ["encoding", "ureq", "zip"]
compress = ["lindera-cc-cedict-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1.3"

lindera-core = { version = "0.12.2", path = "../lindera-core" }
lindera-decompress = { version = "0.12.2", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2", optional = true }
ureq = { version = "2.4.0", default-features = false, features = ["tls"], optional = true }
zip = { version = "0.6", optional = true }

lindera-core = { version = "0.12.2", path = "../lindera-core" }
lindera-cc-cedict-builder = { version = "0.12.2", path = "../lindera-cc-cedict-builder"}
