[package]
name = "lindera-cc-cedict"
version = "0.27.1"
edition = "2021"
description = "A Japanese morphological dictionary for CC-CEDICT."
documentation = "https://docs.rs/lindera-cc-cedict"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["chinese", "morphological", "dictionary", "cc-cedict"]
categories = ["text-processing"]
license = "MIT"

[features]
cc-cedict = ["encoding", "zip"]
compress = ["lindera-cc-cedict-builder/compress", "lindera-decompress"]

[dependencies]
bincode.workspace = true
byteorder.workspace = true
once_cell.workspace = true

lindera-core.workspace = true
lindera-decompress = { workspace = true, optional = true }

[build-dependencies]
encoding = { workspace = true, optional = true }
zip = { workspace = true, optional = true }

lindera-core.workspace = true
lindera-cc-cedict-builder.workspace = true
