[package]
name = "lindera-cc-cedict"
version = "0.17.0"
edition = "2021"
description = "A Japanese morphological dictionary for CC-CEDICT."
documentation = "https://docs.rs/lindera-cc-cedict"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["chinese", "morphological", "dictionary", "loader", "cc-cedict"]
categories = ["text-processing"]
license = "MIT"

[features]
cc-cedict = ["encoding", "zip"]
compress = ["lindera-cc-cedict-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
once_cell = "1.12.0"

lindera-core = { version = "0.17.0", path = "../lindera-core" }
lindera-decompress = { version = "0.17.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2.33", optional = true }
zip = { version = "0.6.2", optional = true }

lindera-core = { version = "0.17.0", path = "../lindera-core" }
lindera-cc-cedict-builder = { version = "0.17.0", path = "../lindera-cc-cedict-builder"}
