[package]
name = "lindera"
version = "0.17.0"
edition = "2021"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
default = ["ipadic"]  # ipadic is the default feature
cjk = ["ipadic", "ko-dic", "cc-cedict"]
full = ["ipadic", "unidic", "ko-dic", "cc-cedict"]
ipadic = ["lindera-ipadic/ipadic"]  # Japanese dictionary
unidic = ["lindera-unidic/unidic"]  # Japanese dictionary
ko-dic = ["lindera-ko-dic/ko-dic"]  # Korean dictionary
cc-cedict = ["lindera-cc-cedict/cc-cedict"]  # Chinese dictionary
compress = ["lindera-ipadic/compress", "lindera-unidic/compress"]

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
byteorder = "1.4.3"
encoding = "0.2.33"
serde = {version="1.0.138", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"

lindera-core = { version = "0.17.0", path = "../lindera-core" }
lindera-dictionary = { version = "0.17.0", path = "../lindera-dictionary" }
lindera-ipadic = { version = "0.17.0", path = "../lindera-ipadic", optional = true }
lindera-ipadic-builder = { version = "0.17.0", path = "../lindera-ipadic-builder" }
lindera-unidic = { version = "0.17.0", path = "../lindera-unidic", optional = true }
lindera-unidic-builder = { version = "0.17.0", path = "../lindera-unidic-builder" }
lindera-ko-dic = { version = "0.17.0", path = "../lindera-ko-dic", optional = true }
lindera-ko-dic-builder = { version = "0.17.0", path = "../lindera-ko-dic-builder" }
lindera-cc-cedict = { version = "0.17.0", path = "../lindera-cc-cedict", optional = true }
lindera-cc-cedict-builder = { version = "0.17.0", path = "../lindera-cc-cedict-builder" }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
