[package]
name = "lindera"
version = "0.21.1"
edition = "2021"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
ipadic = ["lindera-dictionary/ipadic", "lindera-filter/ipadic"]  # Japanese dictionary included
unidic = ["lindera-dictionary/unidic", "lindera-filter/unidic"]  # Japanese dictionary included
ko-dic = ["lindera-dictionary/ko-dic", "lindera-filter/ko-dic"]  # Korean dictionary included
cc-cedict = ["lindera-dictionary/cc-cedict"]  # Chinese dictionary included
ipadic-compress = ["lindera-dictionary/ipadic-compress"]
unidic-compress = ["lindera-dictionary/unidic-compress"]
ko-dic-compress = ["lindera-dictionary/ko-dic-compress"]
cc-cedict-compress = ["lindera-dictionary/cc-cedict-compress"]

[dependencies]
anyhow = "1.0.68"
bincode = "1.3.3"
byteorder = "1.4.3"
encoding = "0.2.33"
kanaria = "0.2.0"
regex = "1.7.1"
serde = {version="1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
unicode-blocks = "0.1.5"
unicode-normalization = "0.1.22"
yada = "0.5.0"

lindera-cc-cedict-builder = { version = "0.21.0", path = "../lindera-cc-cedict-builder" }
lindera-core = { version = "0.21.0", path = "../lindera-core" }
lindera-dictionary = { version = "0.21.0", path = "../lindera-dictionary" }
lindera-ipadic-builder = { version = "0.21.0", path = "../lindera-ipadic-builder" }
lindera-ko-dic-builder = { version = "0.21.0", path = "../lindera-ko-dic-builder" }
lindera-unidic-builder = { version = "0.21.0", path = "../lindera-unidic-builder" }
lindera-filter = { version = "0.21.0", path = "../lindera-filter" }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
once_cell = "1.17.0"

[[bench]]
name = "bench"
harness = false
