[package]
name = "lindera"
version = "0.21.1"
edition = "2021"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
all-dictionaries = ["ipadic", "unidic", "ko-dic", "cc-cedict"]  # All dictionaries included
cjk = ["cc-cedict", "ipadic", "ko-dic"] # CJK dictionaries included
ipadic = ["lindera-ipadic/ipadic"]  # Japanese dictionary included
unidic = ["lindera-unidic/unidic"]  # Japanese dictionary included
ko-dic = ["lindera-ko-dic/ko-dic"]  # Korean dictionary included
cc-cedict = ["lindera-cc-cedict/cc-cedict"]  # Chinese dictionary included
compress = ["lindera-ipadic/compress", "lindera-unidic/compress"]

[dependencies]
anyhow = "1.0.68"
bincode = "1.3.3"
byteorder = "1.4.3"
encoding = "0.2.33"
kanaria = "0.2.0"
regex = "1.7.1"
serde = {version="1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
unicode-blocks = "0.1.5"
unicode-normalization = "0.1.22"
yada = "0.5.0"

lindera-cc-cedict = { version = "0.21.0", path = "../lindera-cc-cedict", optional = true }
lindera-cc-cedict-builder = { version = "0.21.0", path = "../lindera-cc-cedict-builder" }
lindera-core = { version = "0.21.0", path = "../lindera-core" }
lindera-dictionary = { version = "0.21.0", path = "../lindera-dictionary" }
lindera-ipadic = { version = "0.21.0", path = "../lindera-ipadic" }
lindera-ipadic-builder = { version = "0.21.0", path = "../lindera-ipadic-builder" }
lindera-ko-dic = { version = "0.21.0", path = "../lindera-ko-dic", optional = true }
lindera-ko-dic-builder = { version = "0.21.0", path = "../lindera-ko-dic-builder" }
lindera-unidic = { version = "0.21.0", path = "../lindera-unidic", optional = true }
lindera-unidic-builder = { version = "0.21.0", path = "../lindera-unidic-builder" }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
once_cell = "1.17.0"

[[bench]]
name = "bench"
harness = false
