[package]
name = "lindera"
version = "0.9.0"
edition = "2021"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
byteorder = "1.4"
encoding = "0.2"
serde = {version="1.0", features = ["derive"] }
serde_json = "1.0"

lindera-core = { version = "0.9.0", path = "../lindera-core" }
lindera-dictionary = { version = "0.9.0", path = "../lindera-dictionary" }
lindera-ipadic = { version = "0.9.0", path = "../lindera-ipadic" }
lindera-ipadic-builder = { version = "0.9.0", path = "../lindera-ipadic-builder" }


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
