[package]
name = "lindera-ipadic"
version = "0.12.1"
edition = "2021"
description = "A Japanese morphological dictionary for IPADIC."
documentation = "https://docs.rs/lindera-ipadic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "loader", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[features]
ipadic = ["encoding", "flate2", "tar", "ureq"]
compress = ["lindera-ipadic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1.3"

lindera-core = { version = "0.12.1", path = "../lindera-core" }
lindera-decompress = { version = "0.12.1", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2", optional = true }
flate2 = { version = "1.0", optional = true }
tar = { version = "0.4", optional = true }
ureq = { version = "2.4.0", default-features = false, features = ["tls"], optional = true }

lindera-core = { version = "0.12.1", path = "../lindera-core" }
lindera-ipadic-builder = { version = "0.12.1", path = "../lindera-ipadic-builder"}
