[package]
name = "lindera-ipadic"
version = "0.17.0"
edition = "2021"
description = "A Japanese morphological dictionary for IPADIC."
documentation = "https://docs.rs/lindera-ipadic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "loader", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[features]
ipadic = ["encoding", "flate2", "tar"]
compress = ["lindera-ipadic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
once_cell = "1.12.0"

lindera-core = { version = "0.17.0", path = "../lindera-core" }
lindera-decompress = { version = "0.17.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2.33", optional = true }
flate2 = { version = "1.0.24", optional = true }
tar = { version = "0.4.38", optional = true }

lindera-core = { version = "0.17.0", path = "../lindera-core" }
lindera-ipadic-builder = { version = "0.17.0", path = "../lindera-ipadic-builder"}
