[package]
name = "lindera-ipadic"
version = "0.12.0"
edition = "2021"
description = "A Japanese morphological dictionary for IPADIC."
documentation = "https://docs.rs/lindera-ipadic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "loader", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[features]
ipadic = []
compress = ["lindera-ipadic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1.3"

lindera-core = { version = "0.12.0", path = "../lindera-core" }
lindera-decompress = { version = "0.12.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = "0.2"
flate2 = "1.0"
reqwest = "0.11"
tar = "0.4"
tokio = { version = "1.9", features = ["full"] }

lindera-core = { version = "0.12.0", path = "../lindera-core" }
lindera-ipadic-builder = { version = "0.12.0", path = "../lindera-ipadic-builder"}
