[package]
name = "lindera-ipadic-neologd"
version = "0.24.0"
edition = "2021"
description = "A Japanese morphological dictionary for IPADIC NEologd."
documentation = "https://docs.rs/lindera-ipadic-neologd"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "ipadic", "neologd"]
categories = ["text-processing"]
license = "MIT"

[features]
ipadic-neologd = ["encoding", "flate2", "tar"]
compress = ["lindera-ipadic-neologd-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
once_cell = "1.17.0"

lindera-core = { version = "0.24.0", path = "../lindera-core" }
lindera-decompress = { version = "0.24.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2.33", optional = true }
flate2 = { version = "1.0.25", optional = true }
tar = { version = "0.4.38", optional = true }

lindera-core = { version = "0.24.0", path = "../lindera-core" }
lindera-ipadic-neologd-builder = { version = "0.24.0", path = "../lindera-ipadic-neologd-builder"}
