[package]
name = "lindera-ipadic-neologd"
version = "0.30.0"
edition = "2021"
description = "A Japanese morphological dictionary for IPADIC NEologd."
documentation = "https://docs.rs/lindera-ipadic-neologd"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "ipadic", "neologd"]
categories = ["text-processing"]
license = "MIT"

[features]
ipadic-neologd = ["encoding", "flate2", "tar", "ureq"]
compress = ["lindera-ipadic-neologd-builder/compress", "lindera-decompress"]

[dependencies]
bincode.workspace = true
byteorder.workspace = true
once_cell.workspace = true

lindera-core.workspace = true
lindera-decompress = { workspace = true, optional = true }

[build-dependencies]
encoding = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }
ureq = { workspace = true, optional = true }

lindera-core.workspace = true
lindera-ipadic-neologd-builder.workspace = true
