[package]
name = "lindera-ko-dic"
version = "0.11.0"
edition = "2021"
description = "A Japanese morphological dictionary for ko-dic."
documentation = "https://docs.rs/lindera-ko-dic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["korean", "morphological", "dictionary", "loader", "ko-dic"]
categories = ["text-processing"]
license = "MIT"

[features]
compress = ["lindera-ko-dic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1"

lindera-core = { version = "0.11.0", path = "../lindera-core" }
lindera-decompress = { version = "0.11.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = "0.2"
flate2 = "1.0"
reqwest = "0.11"
tar = "0.4"
tokio = { version = "1.9", features = ["full"] }

lindera-core = { version = "0.11.0", path = "../lindera-core" }
lindera-ko-dic-builder = { version = "0.11.0", path = "../lindera-ko-dic-builder"}
