[package]
name = "lindera-ko-dic"
version = "0.12.0"
edition = "2021"
description = "A Japanese morphological dictionary for ko-dic."
documentation = "https://docs.rs/lindera-ko-dic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["korean", "morphological", "dictionary", "loader", "ko-dic"]
categories = ["text-processing"]
license = "MIT"

[features]
ko-dic = ["encoding", "flate2", "tar", "ureq"]
compress = ["lindera-ko-dic-builder/compress", "lindera-decompress"]

[dependencies]
bincode = "1.3"
byteorder = "1.4"
once_cell = "1.3"

lindera-core = { version = "0.12.0", path = "../lindera-core" }
lindera-decompress = { version = "0.12.0", path = "../lindera-decompress", optional = true }

[build-dependencies]
encoding = { version = "0.2", optional = true }
flate2 = { version = "1.0", optional = true }
tar = { version = "0.4", optional = true }
ureq = { version = "2.4.0", default-features = false, features = ["tls"], optional = true }

lindera-core = { version = "0.12.0", path = "../lindera-core" }
lindera-ko-dic-builder = { version = "0.12.0", path = "../lindera-ko-dic-builder"}
