[package]
name = "lindera-ko-dic"
version = "0.27.1"
edition = "2021"
description = "A Japanese morphological dictionary for ko-dic."
documentation = "https://docs.rs/lindera-ko-dic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["korean", "morphological", "dictionary", "ko-dic"]
categories = ["text-processing"]
license = "MIT"

[features]
ko-dic = ["encoding", "flate2", "tar"]
compress = ["lindera-ko-dic-builder/compress", "lindera-decompress"]

[dependencies]
bincode.workspace = true
byteorder.workspace = true
once_cell.workspace = true

lindera-core.workspace = true
lindera-decompress = { workspace = true, optional = true }

[build-dependencies]
encoding = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }

lindera-core.workspace = true
lindera-ko-dic-builder.workspace = true
