[package]
name = "lindera-filter"
version = "0.26.0"
edition = "2021"
description = "Character and token filters for Lindera."
documentation = "https://docs.rs/lindera-filter"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
ipadic = ["lindera-dictionary/ipadic"]  # Japanese dictionary included
ipadic-filter = []
ipadic-neologd = ["lindera-dictionary/ipadic-neologd"]  # Japanese dictionary included
ipadic-neologd-filter = []
unidic = ["lindera-dictionary/unidic"]  # Japanese dictionary included
unidic-filter = []
ko-dic = ["lindera-dictionary/ko-dic"]  # Korean dictionary included
ko-dic-filter = []
cc-cedict = ["lindera-dictionary/cc-cedict"]  # Chinese dictionary included
cc-cedict-filter = []

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
byteorder = "1.4.3"
kanaria = "0.2.0"
once_cell = "1.18.0"
regex = "1.9.0"
serde = { version="1.0.167", features = ["derive"] }
serde_json = "1.0.100"
unicode-blocks = "0.1.8"
unicode-normalization = "0.1.22"
unicode-segmentation = "1.10.1"
yada = "0.5.0"

lindera-core = { version = "0.26.0", path = "../lindera-core" }
lindera-dictionary = { version = "0.26.0", path = "../lindera-dictionary" }
lindera-tokenizer = { version = "0.26.0", path = "../lindera-tokenizer" }

[dev-dependencies]
once_cell = "1.18.0"
