[package]
name = "lindera-ipadic-builder"
version = "0.9.0"
edition = "2021"
description = "A Japanese morphological dictionary builder for IPADIC."
documentation = "https://docs.rs/lindera-ipadic-builder"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "builder", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
byteorder = "1.4"
clap = { version = "3.1", features = ["derive"] }
encoding = "0.2"
glob = "0.3"
serde = "1.0"
yada = "0.5"

lindera-core = { version = "0.9.0", path = "../lindera-core" }
lindera-decompress = { version = "0.9.0", path = "../lindera-decompress" }
lindera-compress = { version = "0.9.0", path = "../lindera-compress" }

[[bin]]
name = "lindera-ipadic-builder"
path = "src/main.rs"
