[package]
name = "lindera-ipadic-builder"
version = "0.7.1"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>",
    "Tomoko Uchida <tomoko.uchida.1111@gmail.com>",
    "Jun Ohtani <johtani@gmail.com>"
    ]
edition = "2018"
description = "A Japanese morphological dictionary builder for IPADIC."
documentation = "https://docs.rs/lindera-ipadic-builder"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/linderalindera-ipadic-builder"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "builder", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
byteorder = "1.4"
clap = "2.33"
encoding = "0.2"
glob = "0.3"
serde = "1.0"
thiserror = "1.0"
yada = "0.4"

lindera-core = { version = "0.7", path = "../lindera-core" }

[[bin]]
name = "lindera-ipadic"
path = "src/main.rs"
