name: Periodic

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * SUN

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        toolchain: [stable, beta, nightly]
        features: ["ipadic", "ko-dic", "cc-cedict"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - name: Run test
        run: cargo test --features "${{ matrix.features }}"
